// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package server

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/internal/logic/model"
	"github.com/admgo/admgo/services/cmdb/rpc/internal/svc"
	"github.com/admgo/admgo/services/cmdb/rpc/pb/pb"
)

type ModelServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedModelServer
}

func NewModelServer(svcCtx *svc.ServiceContext) *ModelServer {
	return &ModelServer{
		svcCtx: svcCtx,
	}
}

// 创建资源模型
func (s *ModelServer) CreateResourceModel(ctx context.Context, in *pb.CreateModelRequest) (*pb.CreateModelResponse, error) {
	l := modellogic.NewCreateResourceModelLogic(ctx, s.svcCtx)
	return l.CreateResourceModel(in)
}
