// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package server

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/internal/logic/attribute"
	"github.com/admgo/admgo/services/cmdb/rpc/internal/svc"
	"github.com/admgo/admgo/services/cmdb/rpc/pb/pb"
)

type AttributeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAttributeServer
}

func NewAttributeServer(svcCtx *svc.ServiceContext) *AttributeServer {
	return &AttributeServer{
		svcCtx: svcCtx,
	}
}

// 创建资源属性
func (s *AttributeServer) CreateResourceAttribute(ctx context.Context, in *pb.CreateAttributeRequest) (*pb.CreateAttributeResponse, error) {
	l := attributelogic.NewCreateResourceAttributeLogic(ctx, s.svcCtx)
	return l.CreateResourceAttribute(in)
}
