// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package category

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateAttributeRequest      = pb.CreateAttributeRequest
	CreateAttributeResponse     = pb.CreateAttributeResponse
	CreateAttributeTypeRequest  = pb.CreateAttributeTypeRequest
	CreateAttributeTypeResponse = pb.CreateAttributeTypeResponse
	CreateCategoryRequest       = pb.CreateCategoryRequest
	CreateCategoryResponse      = pb.CreateCategoryResponse
	CreateModelRequest          = pb.CreateModelRequest
	CreateModelResponse         = pb.CreateModelResponse
	CreateResourceGroupRequest  = pb.CreateResourceGroupRequest
	CreateResourceGroupResponse = pb.CreateResourceGroupResponse
	CreateResourceRequest       = pb.CreateResourceRequest
	CreateResourceResponse      = pb.CreateResourceResponse

	Category interface {
		// 创建资源类型
		CreateResourceType(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	}

	defaultCategory struct {
		cli zrpc.Client
	}
)

func NewCategory(cli zrpc.Client) Category {
	return &defaultCategory{
		cli: cli,
	}
}

// 创建资源类型
func (m *defaultCategory) CreateResourceType(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	client := pb.NewCategoryClient(m.cli.Conn())
	return client.CreateResourceType(ctx, in, opts...)
}
