// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package server

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/internal/logic/category"
	"github.com/admgo/admgo/services/cmdb/rpc/internal/svc"
	"github.com/admgo/admgo/services/cmdb/rpc/pb/pb"
)

type CategoryServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCategoryServer
}

func NewCategoryServer(svcCtx *svc.ServiceContext) *CategoryServer {
	return &CategoryServer{
		svcCtx: svcCtx,
	}
}

// 创建资源类型
func (s *CategoryServer) CreateResourceType(ctx context.Context, in *pb.CreateCategoryRequest) (*pb.CreateCategoryResponse, error) {
	l := categorylogic.NewCreateResourceTypeLogic(ctx, s.svcCtx)
	return l.CreateResourceType(in)
}
