// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"github.com/admgo/admgo/services/user/rpc/internal/logic"
	"github.com/admgo/admgo/services/user/rpc/internal/svc"
	"github.com/admgo/admgo/services/user/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 创建用户
func (s *UserServer) CreateUser(ctx context.Context, in *pb.CreateUserRequest) (*pb.CreateUserResponse, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

// 根据用户ID查找指定用户
func (s *UserServer) FindSingleUserByUserID(ctx context.Context, in *pb.FindSingleUserByUserIDRequest) (*pb.FindSingleUserByUserIDResponse, error) {
	l := logic.NewFindSingleUserByUserIDLogic(ctx, s.svcCtx)
	return l.FindSingleUserByUserID(in)
}

// 根据用户名密码查找指定用户
func (s *UserServer) FindSingleUserByUsernameAndPassword(ctx context.Context, in *pb.FindSingleUserByUsernameAndPasswordRequest) (*pb.FindSingleUserByUsernameAndPasswordResponse, error) {
	l := logic.NewFindSingleUserByUsernameAndPasswordLogic(ctx, s.svcCtx)
	return l.FindSingleUserByUsernameAndPassword(in)
}

// 查找所有用户
func (s *UserServer) FindAllUser(ctx context.Context, in *pb.FindAllUserRequest) (*pb.FindAllUserResponse, error) {
	l := logic.NewFindAllUserLogic(ctx, s.svcCtx)
	return l.FindAllUser(in)
}

// 删除用户
func (s *UserServer) DeleteUser(ctx context.Context, in *pb.DeleteUserRequest) (*pb.DeleteUserResponse, error) {
	l := logic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}

// 更新用户信息（包括邮箱、用户名称等）
func (s *UserServer) UpdateUserInfo(ctx context.Context, in *pb.UpdateUserInfoRequest) (*pb.UpdateUserInfoResponse, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

// 更新用户邮箱
func (s *UserServer) UpdateUserEmail(ctx context.Context, in *pb.UpdateUserEmailRequest) (*pb.UpdateUserEmailResponse, error) {
	l := logic.NewUpdateUserEmailLogic(ctx, s.svcCtx)
	return l.UpdateUserEmail(in)
}

// 更新用户名称
func (s *UserServer) UpdateUserName(ctx context.Context, in *pb.UpdateUserNameRequest) (*pb.UpdateUserNameResponse, error) {
	l := logic.NewUpdateUserNameLogic(ctx, s.svcCtx)
	return l.UpdateUserName(in)
}

// 更新用户手机号
func (s *UserServer) UpdateUserPhone(ctx context.Context, in *pb.UpdateUserPhoneRequest) (*pb.UpdateUserPhoneResponse, error) {
	l := logic.NewUpdateUserPhoneLogic(ctx, s.svcCtx)
	return l.UpdateUserPhone(in)
}

// 更新用户员工号
func (s *UserServer) UpdateUserEmployeeNumber(ctx context.Context, in *pb.UpdateUserEmployeeNumberRequest) (*pb.UpdateUserEmployeeNumberResponse, error) {
	l := logic.NewUpdateUserEmployeeNumberLogic(ctx, s.svcCtx)
	return l.UpdateUserEmployeeNumber(in)
}
