// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package resourcegroup

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateAttributeRequest      = pb.CreateAttributeRequest
	CreateAttributeResponse     = pb.CreateAttributeResponse
	CreateAttributeTypeRequest  = pb.CreateAttributeTypeRequest
	CreateAttributeTypeResponse = pb.CreateAttributeTypeResponse
	CreateCategoryRequest       = pb.CreateCategoryRequest
	CreateCategoryResponse      = pb.CreateCategoryResponse
	CreateModelRequest          = pb.CreateModelRequest
	CreateModelResponse         = pb.CreateModelResponse
	CreateResourceGroupRequest  = pb.CreateResourceGroupRequest
	CreateResourceGroupResponse = pb.CreateResourceGroupResponse
	CreateResourceRequest       = pb.CreateResourceRequest
	CreateResourceResponse      = pb.CreateResourceResponse

	ResourceGroup interface {
		// 创建资源组
		CreateResourceGroup(ctx context.Context, in *CreateResourceGroupRequest, opts ...grpc.CallOption) (*CreateResourceGroupResponse, error)
	}

	defaultResourceGroup struct {
		cli zrpc.Client
	}
)

func NewResourceGroup(cli zrpc.Client) ResourceGroup {
	return &defaultResourceGroup{
		cli: cli,
	}
}

// 创建资源组
func (m *defaultResourceGroup) CreateResourceGroup(ctx context.Context, in *CreateResourceGroupRequest, opts ...grpc.CallOption) (*CreateResourceGroupResponse, error) {
	client := pb.NewResourceGroupClient(m.cli.Conn())
	return client.CreateResourceGroup(ctx, in, opts...)
}
