// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package server

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/internal/logic/resource"
	"github.com/admgo/admgo/services/cmdb/rpc/internal/svc"
	"github.com/admgo/admgo/services/cmdb/rpc/pb/pb"
)

type ResourceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedResourceServer
}

func NewResourceServer(svcCtx *svc.ServiceContext) *ResourceServer {
	return &ResourceServer{
		svcCtx: svcCtx,
	}
}

// 创建资源
func (s *ResourceServer) CreateResource(ctx context.Context, in *pb.CreateResourceRequest) (*pb.CreateResourceResponse, error) {
	l := resourcelogic.NewCreateResourceLogic(ctx, s.svcCtx)
	return l.CreateResource(in)
}
