// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserName string `json:"username,optional,omitempty" validate:"required"`
	PassWord string `json:"password,optional,omitempty"`
}

type LoginRsp struct {
}

type LogoutReq struct {
}

type LogoutRsp struct {
}

type RegisterReq struct {
	UserName string `json:"username,optional,omitempty" validate:"required"`
	PassWord string `json:"password,optional,omitempty"`
}

type RegisterRsp struct {
}

type SessionReq struct {
	UserName string `json:"username,optional,omitempty" validate:"required"`
	PassWord string `json:"password,optional,omitempty"`
}

type SessionRsp struct {
}

type TokenReq struct {
	UserName string `json:"username,optional,omitempty" validate:"required"`
	PassWord string `json:"password,optional,omitempty"`
}

type TokenRsp struct {
}
