// Code generated by goctl. DO NOT EDIT.
// Source: cmdb.proto

package attribute

import (
	"context"

	"github.com/admgo/admgo/services/cmdb/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateAttributeRequest      = pb.CreateAttributeRequest
	CreateAttributeResponse     = pb.CreateAttributeResponse
	CreateAttributeTypeRequest  = pb.CreateAttributeTypeRequest
	CreateAttributeTypeResponse = pb.CreateAttributeTypeResponse
	CreateCategoryRequest       = pb.CreateCategoryRequest
	CreateCategoryResponse      = pb.CreateCategoryResponse
	CreateModelRequest          = pb.CreateModelRequest
	CreateModelResponse         = pb.CreateModelResponse
	CreateResourceGroupRequest  = pb.CreateResourceGroupRequest
	CreateResourceGroupResponse = pb.CreateResourceGroupResponse
	CreateResourceRequest       = pb.CreateResourceRequest
	CreateResourceResponse      = pb.CreateResourceResponse

	Attribute interface {
		// 创建资源属性
		CreateResourceAttribute(ctx context.Context, in *CreateAttributeRequest, opts ...grpc.CallOption) (*CreateAttributeResponse, error)
	}

	defaultAttribute struct {
		cli zrpc.Client
	}
)

func NewAttribute(cli zrpc.Client) Attribute {
	return &defaultAttribute{
		cli: cli,
	}
}

// 创建资源属性
func (m *defaultAttribute) CreateResourceAttribute(ctx context.Context, in *CreateAttributeRequest, opts ...grpc.CallOption) (*CreateAttributeResponse, error) {
	client := pb.NewAttributeClient(m.cli.Conn())
	return client.CreateResourceAttribute(ctx, in, opts...)
}
